import { sql } from 'drizzle-orm'
import { drizzle } from 'drizzle-orm/node-postgres'
import { Pool, type PoolConfig } from 'pg'
import * as schema from './schema'

let cachedPool: Pool | null = null
let cachedDb: ReturnType<typeof createDemoDatabase> | null = null
let cachedMigration: Promise<void> | null = null

function createDemoDatabase() {
  const pool = getPool()
  return drizzle(pool, { schema })
}

export type DemoDatabase = ReturnType<typeof createDemoDatabase>

export function getDemoDatabase(): DemoDatabase {
  if (!cachedDb) {
    cachedDb = createDemoDatabase()
  }
  return cachedDb
}

export async function ensureDemoDatabase(): Promise<DemoDatabase> {
  const db = getDemoDatabase()
  if (!cachedMigration) {
    cachedMigration = migrate(db)
  }
  await cachedMigration
  return db
}

export async function closeDemoDatabaseForTests(): Promise<void> {
  await cachedPool?.end()
  cachedPool = null
  cachedDb = null
  cachedMigration = null
}

function getPool(): Pool {
  if (!cachedPool) {
    const connectionString = resolveDatabaseUrl()
    cachedPool = new Pool({
      connectionString,
      idleTimeoutMillis: 10_000,
      connectionTimeoutMillis: 10_000,
      max: resolvePoolMax(),
      ssl: resolveSsl(connectionString),
    })
  }
  return cachedPool
}

function resolveDatabaseUrl(): string {
  const value =
    process.env.DATABASE_URL ?? process.env.POSTGRES_URL ?? process.env.POSTGRES_PRISMA_URL
  if (!value) {
    throw new Error('DATABASE_URL or POSTGRES_URL is required for the demo Postgres scene store')
  }
  return value
}

function resolvePoolMax(): number {
  const parsed = Number.parseInt(process.env.PASCAL_DEMO_PG_POOL_MAX ?? '5', 10)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : 5
}

function resolveSsl(connectionString: string): PoolConfig['ssl'] | undefined {
  let url: URL
  try {
    url = new URL(connectionString)
  } catch {
    return undefined
  }

  const sslMode = url.searchParams.get('sslmode')
  if (sslMode === 'disable') return undefined
  if (sslMode) return { rejectUnauthorized: false }

  const host = url.hostname.toLowerCase()
  if (host === 'localhost' || host === '127.0.0.1' || host === '::1') {
    return undefined
  }
  return { rejectUnauthorized: false }
}

async function migrate(db: DemoDatabase): Promise<void> {
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS pascal_demo_scenes (
      id text PRIMARY KEY,
      name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 200),
      project_id text,
      owner_id text,
      thumbnail_url text,
      version integer NOT NULL CHECK (version >= 1),
      created_at timestamptz NOT NULL,
      updated_at timestamptz NOT NULL,
      size_bytes integer NOT NULL CHECK (size_bytes >= 0),
      node_count integer NOT NULL CHECK (node_count >= 0),
      graph_json jsonb NOT NULL
    )
  `)

  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS pascal_demo_scenes_project_updated_idx
      ON pascal_demo_scenes(project_id, updated_at DESC)
  `)

  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS pascal_demo_scenes_owner_updated_idx
      ON pascal_demo_scenes(owner_id, updated_at DESC)
  `)

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS pascal_demo_scene_revisions (
      scene_id text NOT NULL REFERENCES pascal_demo_scenes(id) ON DELETE CASCADE,
      version integer NOT NULL CHECK (version >= 1),
      graph_json jsonb NOT NULL,
      author_kind text NOT NULL,
      author_id text,
      created_at timestamptz NOT NULL,
      PRIMARY KEY (scene_id, version)
    )
  `)

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS pascal_demo_scene_events (
      event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      scene_id text NOT NULL REFERENCES pascal_demo_scenes(id) ON DELETE CASCADE,
      version integer NOT NULL CHECK (version >= 1),
      kind text NOT NULL,
      created_at timestamptz NOT NULL,
      graph_json jsonb NOT NULL
    )
  `)

  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS pascal_demo_scene_events_scene_event_idx
      ON pascal_demo_scene_events(scene_id, event_id)
  `)

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS pascal_demo_llm_config (
      id text PRIMARY KEY,
      enabled boolean NOT NULL,
      provider text NOT NULL,
      model text NOT NULL,
      base_url text,
      api_key_env_var text NOT NULL,
      temperature real NOT NULL,
      max_tool_iterations integer NOT NULL CHECK (max_tool_iterations BETWEEN 1 AND 30),
      fallback_on_error boolean NOT NULL,
      created_at timestamptz NOT NULL,
      updated_at timestamptz NOT NULL
    )
  `)
}
